select * from BUSINESS_SALES_TRANSACTION where COUNTRY='Australia';

select COUNTRY from BUSINESS_SALES_TRANSACTION order by COUNTRY;

select COUNT(PRODUCTNAME) 
from BUSINESS_SALES_TRANSACTION
where TRANSACTIONDATE like '%17' or TRANSACTIONDATE like '%18';

select PRODUCTNAME from BUSINESS_SALES_TRANSACTION where PRICE>2.01;

select COUNT(DISTINCT PRODUCTNO) from BUSINESS_SALES_TRANSACTION
where PRICE<2.04;