-- 1.Display the Order details of who are all ordered from country Australia?
SELECT * FROM BUSINESS_SALES_TRANSACTION
WHERE COUNTRY='Australia';

-- 2.Display the Country name in ascending order?
SELECT DISTINCT(COUNTRY) FROM BUSINESS_SALES_TRANSACTION
ORDER BY COUNTRY;

--3. Count the Products sale in years between 2017 and 2018?
SELECT COUNT(PRODUCTNAME)
FROM BUSINESS_SALES_TRANSACTION
WHERE TRANSACTIONDATE LIKE '%17' OR TRANSACTIONDATE LIKE '%18';

--4. Display the product list the price is above 2.01?
SELECT PRODUCTNAME,PRICE
FROM BUSINESS_SALES_TRANSACTION
WHERE PRICE>2.01;

--5. Count the products of price is below 2.04?
SELECT COUNT(DISTINCT PRODUCTNO)
FROM BUSINESS_SALES_TRANSACTION
WHERE PRICE<2.04;